version: 2
workflows:
  version: 2
  '': {jobs: [t]}

jobs:
  t:
    docker: [image: erlang:alpine]
    steps:
    - run: apk update && apk upgrade
    - run: apk add curl ca-certificates git make
    - checkout
    - run: |
        curl -#fSLo /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
        chmod +x /usr/local/bin/rebar3
        rebar3 --version
    - run: |
        rebar3 do fmt, eunit
        ! rebar3 proper
