version: 2
jobs:
  build:
    docker: [image: 'erlang:alpine']
    steps:
    - run: apk update && apk upgrade
    - run: apk add curl ca-certificates git make
    - checkout
    - run: |
        curl -#fSLo /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
        chmod +x /usr/local/bin/rebar3
        rebar3 --version
    - run: |
        rebar3 eunit
        ! rebar3 proper
